baseURL = "https://www.niedermann.dk/"
languageCode = "en-us"
title = "Jesper\r\nNiedermann"
theme = "hyde"

[params]
themeColor = "theme-base-0b"
Copyright = "Ⓒ 2018"
Description = "Code and stuff"

[permalinks]
posts = "/:year/:month/:day/:title/"
other = "/:filename/"

[staticman]
endpoint = "https://api.staticman.net/v2/entry/"
username = "Jeern"
repository = "Niedermann"
branch = "master"