baseURL = "https://www.niedermann.dk/"
languageCode = "en-us"
title = "Jesper\r\nNiedermann"
theme = "hyde"

[params]
themeColor = "theme-base-08"
Copyright = "Ⓒ 2018"
Description = "Code and Tech blog"

