baseURL = "https://www.niedermann.dk"
languageCode = "en-us"
title = "Jesper\r\nNiedermann"
theme = "hyde"
pygmentsCodefences = "true"
enableRobotsTXT = true

[params]
themeColor = "theme-base-0b"
Copyright = "Ⓒ 2018"
Description = "Code and stuff"

[permalinks]
posts = "/:year/:month/:day/:title/"
other = "/:filename/"
